### ISSUE TITLE
[ERROR] Got  an error "Cannot read property 'get' of undefined" when subscribing FilterService.selectedImage$

### ISSUE THREAD

**Issue by syiwawahyu** [JayKan/angular2-instagram-core#17]
Hi JayKan, 

I started to use your plugin for my application, your plugin was pretty good but we need a documentation. I tried to analyze the code and tried to use it, and I found an error like this.
![image](https://user-images.githubusercontent.com/13311831/37080546-3b11313a-2219-11e8-835c-9c937faf0f96.png)
Here is what I did.
![image](https://user-images.githubusercontent.com/13311831/37080573-57f2f004-2219-11e8-96e2-f5caca9b3e42.png)
![image](https://user-images.githubusercontent.com/13311831/37080583-61c24e04-2219-11e8-85f2-161bcc011cf6.png)
And we got "undefined" on this part 
![image](https://user-images.githubusercontent.com/13311831/37080634-81e9de40-2219-11e8-868e-1de050ccadaa.png)

Can you help me by showing me which step I miss or if that were bug, would you please to fix it?

Thanks before.

**Comment by syiwawahyu** [comment]
Oh, I'm sorry i missed filtersReducer on my module. It's done now.
`StoreModule.provideStore({
        filters: filtersReducer,
})`

**Comment by JayKan** [comment]
@syiwawahyu I'm glad you've found this repo to be useful; let me know if you are running into any other issues 👍
